### ISSUE TITLE
Otel4s 0.5.0 upgrade artifacts didn't publish

### ISSUE THREAD

**Issue by ryanfreeth** [http4s/http4s-otel4s-middleware#68]
Hey @NthPortal,

If I am reading this correctly it looks like the artifacts didn't publish for your recently update to Otel4s 0.5.0 https://github.com/http4s/http4s-otel4s-middleware/actions/runs/8545349496/job/23413537576#step:11:13

We make heavy use of this middleware at $work and would love to upgrade as soon as we can. 

If there is something I can do here to help please let me know.
Thanks!

**Comment by 2m** [comment]
The artifacts for [`0.4.0-beta.1`](https://mvnrepository.com/artifact/org.http4s/http4s-otel4s-middleware_3/0.4.0-beta.1) are in the Maven Central and that is depending on otel4s `0.5.0`. I am also quite eager to update, and that version is working without problems.

**Comment by NthPortal** [comment]
I have a bunch of branches in flight, but I don't think this library depends on anything that had breaking binary changes in 0.6.0, so I'll try to update to that as well if desired. though maybe that should be after a release, in case anyone is stuck on 0.5.0?

**Comment by NthPortal** [comment]
is this still an issue for 0.6.0 or the 0.7.0 beta(s)?

**Comment by NthPortal** [comment]
I'm closing this. feel free to reopen if it's an issue for 0.7.x or 0.8.x
